name: Run Tests and Upload Results to Xray

on:
  workflow_dispatch:  # Allows manual triggering from GitHub Actions UI

jobs:
  test-and-report:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Dependencies
      run: npm install
      shell: bash

    - name: Install Playwright Browsers
      run: npx playwright install
      shell: bash 

    - name: Run Tests
      run: npm run test:regression
      shell: bash

    - name: Authenticate with Xray and Get Token
      id: xray_auth
      run: |
        $headers = @{
          "Content-Type" = "application/json"
        }
        
        $body = @{
          "client_id" = "${{ secrets.XRAY_CLIENT_ID }}"
          "client_secret" = "${{ secrets.XRAY_CLIENT_SECRET }}"
        } | ConvertTo-Json
        
        $response = Invoke-RestMethod -Uri "https://xray.cloud.getxray.app/api/v2/authenticate" -Method POST -Headers $headers -Body $body
        echo "TOKEN=$response" >> $env:GITHUB_ENV
      shell: pwsh  # Using PowerShell

     - name: Upload Test Results to Xray
      run: |
        $headers = @{
          "Content-Type" = "application/json"
          "Authorization" = "Bearer ${{ env.TOKEN }}"
        }

        $body = @{
          "testExecutionKey" = "SCRUM-25"   # Replace with actual Test Execution Key
          "tests" = @(
            @{
              "testKey" = "SCRUM-5"
              "status" = "PASSED"
            }
          )
        } | ConvertTo-Json -Depth 10

        $body | Out-File -FilePath xray_payload.json  # Save to file for debugging

        Invoke-RestMethod -Uri "https://xray.cloud.getxray.app/api/v2/import/execution" -Method POST -Headers $headers -Body (Get-Content -Raw xray_payload.json)
      shell: pwsh
