name: Run Tests and Upload Results to Xray

on:
  workflow_dispatch:  # Allows manual triggering from GitHub Actions UI

jobs:
  test-and-report:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Dependencies
      run: npm install
      shell: bash

    - name: Install Playwright Browsers
      run: npx playwright install
      shell: bash 

    - name: Run Tests
      run: npm run test:regression
      shell: bash

   # Add Upload Test Results to Xray here
    - name: Upload Test Results to Xray
      run: |
        # Authenticate with Xray and get token
        TOKEN=$(curl -H "Content-Type: application/json" -X POST "https://xray.cloud.getxray.app/api/v2/authenticate" -d '{"client_id": "${{ secrets.XRAY_CLIENT_ID }}", "client_secret": "${{ secrets.XRAY_CLIENT_SECRET }}"}' | tr -d '"')
        
        # Define the Test Execution Key and Test Results
        TEST_EXECUTION_KEY="NEW_KEY" # Optionally, you can use an existing Test Execution Key
        TEST_RESULTS=$(jq -n \
          --arg key "$TEST_EXECUTION_KEY" \
          '{
            testExecutionKey: $key, 
            tests: [
              { 
                testKey: "SCRUM-5", 
                status: "PASS" 
              }
            ]
          }')
