name: Run Tests and Upload Results to Xray

on:
  push:
    branches:
      - main

jobs:
  test-and-report:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Dependencies
      run: npm install
      shell: bash

    - name: Run Tests
      run: npm run test:regression
      shell: bash

    - name: Upload Test Results to Xray
      run: |
        TOKEN=$(curl -H "Content-Type: application/json" -X POST "https://xray.cloud.getxray.app/api/v2/authenticate" -d '{"client_id": "${{ secrets.XRAY_CLIENT_ID }}", "client_secret": "${{ secrets.XRAY_CLIENT_SECRET }}"}' | tr -d '"')
        
        Invoke-RestMethod -Uri "https://xray.cloud.getxray.app/api/v2/import/execution/cucumber" -Method Post -Headers @{"Content-Type"="application/json"; "Authorization"="Bearer $TOKEN"} -InFile "reports/cucumber-report.json"
        shell: pwsh
